// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMy_jBRQlG-nrImg7v2OPOz5GSqiPNJTs',
    appId: '1:451586664669:android:7b3fa8fdddceb8c49c5334',
    messagingSenderId: '451586664669',
    projectId: 'we-chat-da6fa',
    storageBucket: 'we-chat-da6fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_GZQCy96WoRRXbFakpHWEY4ll0xBBr6o',
    appId: '1:451586664669:ios:4e8a7212c2f6c3d49c5334',
    messagingSenderId: '451586664669',
    projectId: 'we-chat-da6fa',
    storageBucket: 'we-chat-da6fa.appspot.com',
    androidClientId: '451586664669-gfp4ukqvu9ttg49ck96fbd1lfa29vnbc.apps.googleusercontent.com',
    iosClientId: '451586664669-gbv3ci30746isc6d8vacfv29gi4bc8r3.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
